### ISSUE TITLE
Two way binding entry not working

### ISSUE THREAD

**Issue by sinsedrix** [jamesmontemagno/MauiApp-DI#1]
Hi James,

I'd like to test a TwoWay binding on an entry so I added this code to the grid of your MainPage.xaml:
```
            <Entry 
                Grid.Row="5"
                FontSize="18"
                HeightRequest="40"
                Text="{Binding Count, Mode=TwoWay}"
                HorizontalOptions="Center" />
```

When I change the value in the entry, I expect to see a call to the Count setter but nothing happens.
What am I doing wrong?

**Comment by SunshineSpring666** [comment]
to my knowledge, this issue still seems to exist in the latest MAUI release
